// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCc9yatt3lmVyErZHdN8ukAl8mctmVY8',
    appId: '1:616196317928:web:f4233256bac47c63acdf5d',
    messagingSenderId: '616196317928',
    projectId: 'apart-fixmate-app',
    authDomain: 'apart-fixmate-app.firebaseapp.com',
    storageBucket: 'apart-fixmate-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKUu1dOuXFe3rAUYn--MCwHdiM2rd14Q',
    appId: '1:616196317928:android:b1a3f3acf461cf7facdf5d',
    messagingSenderId: '616196317928',
    projectId: 'apart-fixmate-app',
    storageBucket: 'apart-fixmate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9MAG6jrWmwnKq55HJqBaPGesmXeIYK0',
    appId: '1:616196317928:ios:cc92dd2f751c2fcfacdf5d',
    messagingSenderId: '616196317928',
    projectId: 'apart-fixmate-app',
    storageBucket: 'apart-fixmate-app.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI9MAG6jrWmwnKq55HJqBaPGesmXeIYK0',
    appId: '1:616196317928:ios:cc92dd2f751c2fcfacdf5d',
    messagingSenderId: '616196317928',
    projectId: 'apart-fixmate-app',
    storageBucket: 'apart-fixmate-app.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfCc9yatt3lmVyErZHdN8ukAl8mctmVY8',
    appId: '1:616196317928:web:ba3e34493b5edae3acdf5d',
    messagingSenderId: '616196317928',
    projectId: 'apart-fixmate-app',
    authDomain: 'apart-fixmate-app.firebaseapp.com',
    storageBucket: 'apart-fixmate-app.firebasestorage.app',
  );
}
